window.__TOMBOLA_DATA = {
  numbers: [
    { number: 1, italian: "Noicattaro", dialect: "U PAIEI-S DI NAO" },
    { number: 2, italian: "Il cornuto", dialect: "U C-RNEUT" },
    { number: 3, italian: "Le castagne del prete", dialect: null },
    { number: 4, italian: "L'arco di Santoro", dialect: "UARK D SANTAO-R" },
    { number: 5, italian: "Il ferro di cavallo", dialect: "U FIERR D CAVADD" },
    { number: 6, italian: "La fontana delle tartarughe", dialect: "A F-ND-N D S-STU-SCE-N" },
    { number: 7, italian: "L'uva", dialect: "U M-NAVACC" },
    { number: 8, italian: "L'orinale", dialect: "U R-NN-L" },
    { number: 9, italian: "La levatrice", dialect: "A MAMM-R" },
    { number: 10, italian: "La raganella", dialect: "A TROZZUE" },
    { number: 11, italian: "La vecchiaia fetente", dialect: "A V-CCHIE-M F-TEND" },
    { number: 12, italian: "Il monumento", dialect: "U M-N-MENT" },
    { number: 13, italian: "Torre a Mare", dialect: "A P-LAO-S" },
    { number: 14, italian: "La pupa", dialect: "A PEU-P" },
    { number: 15, italian: "La banda", dialect: "A BANN" },
    { number: 16, italian: "La Madonna del Carmine", dialect: "A MADONN DU CAR-M-N" },
    { number: 17, italian: "La peste", dialect: "A PEST" },
    { number: 18, italian: "L'orologio in piazza", dialect: "UARROGG DA CHIAZZ" },
    { number: 19, italian: "Il torchio", dialect: "U TORCHIE" },
    { number: 20, italian: "Il calzone di cipolla", dialect: "U CALZAO-N D C-PODD" },
    { number: 21, italian: "Il latte di mandorle", dialect: "U LATTAMINUE" },
    { number: 22, italian: "Ribelli nel presepe", dialect: null },
    { number: 23, italian: "La pastorale", dialect: "A PASTO-R-L" },
    { number: 24, italian: "La vigilia", dialect: "A V-SCIGGHIE" },
    { number: 25, italian: "Natale", dialect: "NAT-L" },
    { number: 26, italian: "La minestra verde", dialect: "A M-NESTRA VERD" },
    { number: 27, italian: "Il teatro cittadino", dialect: "U TIATR C-TTADEIN" },
    { number: 28, italian: "L'asino", dialect: "U CIUCC D CROCAVECCHIE" },
    { number: 29, italian: "Il falò del giovedì santo", dialect: "A FANAO-V" },
    { number: 30, italian: "La gelosia", dialect: null },
    { number: 31, italian: "La cartomante", dialect: "A M-NARK" },
    { number: 32, italian: "Il braciere", dialect: "A FRASCIAE-R" },
    { number: 33, italian: "Gli anni di Cristo", dialect: "IANN D CRIST" },
    { number: 34, italian: "Il mortaio", dialect: "U M-RT-L" },
    { number: 35, italian: "Il mediatore", dialect: "U ZAN-Z-N" },
    { number: 36, italian: "La villa", dialect: "A PEZZ" },
    { number: 37, italian: "Il secca panni", dialect: null },
    { number: 38, italian: "Il forno a campana", dialect: null },
    { number: 39, italian: "Il trappeto", dialect: "U TRAPPEI-T" },
    { number: 40, italian: "La fornacella", dialect: "A F-RNACEDD" },
    { number: 41, italian: "Il tavoliere", dialect: null },
    { number: 42, italian: "Il figlio celibe", dialect: "U FIGGHIE ASSAU-L" },
    { number: 43, italian: "Le lumache", dialect: null },
    { number: 44, italian: "Il santino", dialect: null },
    { number: 45, italian: "Il mattarello", dialect: null },
    { number: 46, italian: "Il consuolo", dialect: "U CUON-Z" },
    { number: 47, italian: "La ficcanaso", dialect: "A QU-TAO-S" },
    { number: 48, italian: "La mala lingua", dialect: "A MALA LENGUE" },
    { number: 49, italian: "Il cesso", dialect: "U PREI-S" },
    { number: 50, italian: "Le cartellate", dialect: null },
    { number: 51, italian: "Il bisnonno", dialect: null },
    { number: 52, italian: "Lo zio americano", dialect: null },
    { number: 53, italian: "Il pollone", dialect: "U F-NGHIAO-N" },
    { number: 54, italian: "Lo sciuraballo", dialect: null },
    { number: 55, italian: "Pane e pomodoro", dialect: "A CIALLEDD" },
    { number: 56, italian: "Il crocifero", dialect: "U VIACRAO-C" },
    { number: 57, italian: "Il pozzo di San Nicola", dialect: "U PUZZ D SANT N-CAO-L" },
    { number: 58, italian: "Il fazzoletto di stoffa", dialect: "U FAZZ-LETT A REZZ" },
    { number: 59, italian: "La porta a vetri", dialect: "A LASTRIE-R" },
    { number: 60, italian: "La buffetta", dialect: null },
    { number: 61, italian: "L'uomo del frantoio", dialect: "U NAGGHIE-R" },
    { number: 62, italian: "Il secca fiche", dialect: null },
    { number: 63, italian: "Sparatrapp", dialect: "SPARATRAPP" },
    { number: 64, italian: "I lupini", dialect: "I L-PEI-N" },
    { number: 65, italian: "Il monaco", dialect: "U MON-K" },
    { number: 66, italian: "I ceci fritti", dialect: "I CI-C-R FRITT" },
    { number: 67, italian: "Le cartellate", dialect: null },
    { number: 68, italian: "La processione", dialect: "A PR-C-SSAO-N" },
    { number: 69, italian: "Mia suocera", dialect: "S-RO-K-M" },
    { number: 70, italian: "La civetta", dialect: "A K-K-V-SCIE" },
    { number: 71, italian: "La cavallina (gioco)", dialect: "CAVALL E" },
    { number: 72, italian: "Il lupo mannaro", dialect: "U L-POMM" },
    { number: 73, italian: "I cavatelli", dialect: "I MIGNIUCCHIE" },
    { number: 74, italian: "Il raspo", dialect: "U RACIUPP" },
    { number: 75, italian: "Il fornello della cucina", dialect: "PIPIGASS" },
    { number: 76, italian: "La gobba", dialect: "U SCIUMM" },
    { number: 77, italian: "Le gambe delle donne", dialect: "I GAMM DI FE-M-N" },
    { number: 78, italian: "Il velo delle donne in chiesa", dialect: "A VELETT" },
    { number: 79, italian: "Piccolo pezzo di terra", dialect: "U SCIACQUER" },
    { number: 80, italian: "Grattarsi in testa", dialect: "U GRATTIZZ NG-P" },
    { number: 81, italian: "Il ricovero", dialect: "UAESCIE" },
    { number: 82, italian: null, dialect: "A MASCIE-R" },
    { number: 83, italian: "Il pianto", dialect: "U CHIANGIUDD" },
    { number: 84, italian: "Timballo di finocchio lesso", dialect: "U B-N-DITT" },
    { number: 85, italian: "Dolce di castagna", dialect: "A CASTAGNELL" },
    { number: 86, italian: "I soldi", dialect: "I T-RREIS" },
    { number: 87, italian: "La malombra", dialect: "A MALOMBR" },
    { number: 88, italian: "La fuga d'amore", dialect: "A ZEIT SC-NNEU-T" },
    { number: 89, italian: "Il ronzio", dialect: "U RUOSCIE" },
    { number: 90, italian: "Il gaguro", dialect: "U GAGHEUR" }
  ]
};
